export const SET_USER_EMAIL = 'SET_USER_EMAIL';

export const REQUEST_CURRENCIES = 'GET_CURRENCIES';
export const REQUEST_CURRENCIES_ERROR = 'GET_CURRENCIES_ERROR';
export const SET_CURRENCIES = 'SET_CURRENCIES';

export const REQUEST_RATES = 'REQUEST_RATES';
export const REQUEST_RATES_ERROR = 'REQUEST_RATES_ERROR';
export const SET_RATES = 'SET_RATES';

export const SAVE_EXPENSE = 'SAVE_EXPENSE';
